# Generated by Django 5.2.5 on 2025-08-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
    ]
