# Generated by Django 5.2.5 on 2025-09-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_userlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='firstname',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
