# Generated by Django 5.2.5 on 2025-09-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_userlogin_firstname_alter_userlogin_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='lastname',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
