# Generated by Django 5.2.5 on 2025-09-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_userlogin_lastname_alter_userlogin_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='contactdetail',
            field=models.CharField(default='nothing', max_length=15),
        ),
    ]
