# Generated by Django 5.2.5 on 2025-09-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_userlogin_contactdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='email',
            field=models.EmailField(default='null', max_length=254),
        ),
    ]
