# Generated by Django 5.2.5 on 2025-10-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_userlogin_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='UserLogin',
            new_name='UserRegistration',
        ),
    ]
