# Generated by Django 5.2.5 on 2025-10-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_loginauth_rename_userlogin_userregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='contactdetail',
            field=models.CharField(default='xxxxx-xxxxx', max_length=15),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='email',
            field=models.EmailField(default='username@exapmle.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='firstname',
            field=models.CharField(default='John', max_length=50),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='lastname',
            field=models.CharField(default='Doe', max_length=50),
        ),
    ]
